# General purpose diagnostics support library.  Includes actuator state
# machine and other components.

from epicsdbbuilder import records
from builder.device import Device


class supportLib(Device):
    DbdFileList = ['/home/brw82791/epics/Diagnostics/diagTools/dbd/diagToolsSupport.dbd']

    def sub(self, name, **args):
        return records.sub(name, **args)




# Factories for support records

# This state machine reads up to six bits:
#   sense_out      Senses actuator in fully out position
#   sense_pos_1    Sense actuator in position 1 (eg OTR in)
#   sense_pos_2    Sense actuator in position 2 (eg YAG in)
#   command_pos_1  Command actuator to position 1
#   command_pos_2  Command actuator to position 2
#   pressure_low   Detects pressure low condition
# A timeout for allowing movement between commanded states is also specified.
# The record generated by this routine computes the actuator status thus:
#   0 =>  Error state
#   1 =>  Actuator is in out position as commanded
#   2 =>  Actuator is moving between positions
#   3 =>  Actuator is in the first position as commanded
#   4 =>  Actuator is in the second position as commanded.
def ActuatorState(name, timeout,
                  sense_out, sense_pos_1, sense_pos_2,
                  command_pos_1, command_pos_2, pressure_low, **args):
    # Default scan rate of 2Hz
    if not args.has_key('SCAN'):
         args['SCAN'] = '.5 second'
    return supportLib().sub(
        name,
        INAM = 'initMonitorActuatorState',
        SNAM = 'MonitorActuatorState',
        INPA = sense_out,
        INPB = sense_pos_1,
        INPC = sense_pos_2,
        INPD = command_pos_1,
        INPE = command_pos_2,
        INPF = pressure_low,
        INPG = timeout,
        **args)
