#from iocbuilder import *
from epicsdbbuilder import records, PP, CP, ImportRecord
from builder.DLSRecordName import UnsetDevice
from builder.modules.mrfTiming import EventReceiver, EventReceiverVME
from builder.modules.TimingTemplates import MonitorEvent, EvrAlive

from builder.autosave_helper import add_autosave


# Diagnostics timing.
#
# Events common to all Diagnostics IOCs:
#
#   Front panel:
#
#       Output  Source  Description
#
#       TTL 0   DBUS4   1MHz clock
#       TTL 1   (1)     Selected machine clock
#       TTL 2   OTP2    Selected BPM trigger
#       TTL 3   OTP8    Postmortem event
#       TTL 4   PDP1    Radiation Monitor Reset
#       ECL 0   OTP0    Oscilloscope trigger
#       ECL 1
#
#               Width   Delay   Source      Description
#
#       OTP0    10      (2)     (3)         Scope trigger
#       PDP1    297620*420      0x60        1s pulse to reset radmon
#       OTP2    125     (4)     (3)         BPM trigger
#       OTP8    125     234000  0x5E        Post mortem event
#
# Other IOC specific events:
#
#   LI  OTP3    500     9934    0x26        Camera trigger
#       OTP4    500     9934    0x26        Camera trigger
#       OTP10   125     18434   0x26        ADC trigger
#       OTP12   125     18350   0x26        ICT trigger
#       OTP13   125     4934    0x26        PMT beam loss monitors
#
#   BR01
#       OTP3    500     10000   0x26        Camera trigger
#       OTP4    250     0       0x26        Signal generator trigger
#       OTP9    500     12500   0x26        Spare camera trigger
#       OTP10   125     5450000 0x21        Early trigger for ADC
#       OTP12   125     18350   0x26        ICT trigger
#       OTP13   125     5000    0x26        PMT beam loss monitors
#
#   BR03
#       OTP3    500     131700  0x31        Camera trigger
#
#   BS  OTP3    500     131700  0x31        Camera trigger
#       OTP4    1250    (5)     0x32        Kicker synchronised trigger
#       OTP9    500     131700  0x31        Spare camera trigger
#       OTP10   125     138000  0x31        ADC trigger
#       OTP12   125     138300  0x31        ICT trigger
#       OTP13   125     124800  0x31        PMT beam loss monitors
#
#       ECL1    OTP4    Trigger on front panel for kicker synchronsied view
#
#   SR back panel
#       OTP2    125     (4)     (3)         BPM trigger
#       DBUS4                               1MHz clock
#       DBUS6                               Storage ring clockEvrAl
#       OTP8    125     234000  0x5E        Postmortem event
#
#   SR01
#       OTP3    500     131740  0x31        Camera trigger
#       OTP9    500     131740  0x31        Spare camera trigger
#
#   SR10
#       PDP3    6244407 0       0x5F        I10 fast chicaine trigger
#
#   SR23
#       OTP3    125     139250  0x31,0x40   Horizontal and vertical
#       OTP7    125     139250  0x31,0x40   kicker triggers.
#       OTP5    125     5450000 0x20        TMBF trigger
#       OTP9    125     0       0x32        Blanking trigger
#
# Notes:
#
#   (1) DBUS5 (Booster clock) in LI, BR and BS
#       DBUS6 (Storage clock) in SR
#   (2) The scope trigger delay is 25 ticks after the BPM trigger (4)
#   (3) The BPM trigger source is location dependent:
#           LI, BR      0x26
#           BS, SR      0x31
#       This trigger can also be generated from 0x40 or 0x7D.
#   (4) The BPM trigger delay is location dependent:
#           LI, BR      19384
#           BS, SR      139274
#       The trigger delay is also dynamically reprogrammed when the EVR is
#       switched between "Synchronised" and "Normal" modes.
#   (5) The delay for BS.OTP4 tracks SR01S-PC-EVR-01:SET-HW.OTBD
#
#   0x21 = LB0-DI-TRG   Early linac injection trigger, tied to LB-DI-TRG
#   0x26 = LB-DI-TRG    Linac and booster injection trigger for Diagnostics
#   0x31 = BS-DI-TRG    Storage ring injection trigger for Diagnostics
#   0x32 = SR-PRE-INJ   Early storage ring injection event
#   0x40 = SR-DI-TRG    Dedicated Diagnostics software trigger
#   0x5D = BEAM-LOSS    Dedicated Diagnostics hardware trigger
#   0x5E = MPS-TRIP     Machine Protection System trip, triggers beam loss
#   0x5F = I10-FASTCH   10Hz trigger for fast chicaine in I10
#   0x60                Radiation Monitor Reset, resets accumulated dose
#   0x7D = TS-RESET     1Hz UTC synchronous clock



# Machine clock definitions for use by Libera
BoosterClock = EventReceiver.BoosterClock
StorageClock = EventReceiver.StorageClock

LB_Trigger = ('LB-TRG',   EventReceiver.LB_DI_TRG)
BS_Trigger = ('EXTR-PRE', EventReceiver.BS_DI_TRG)


# Number of event clocks per SR turn: four RF cycles per event tick
SR_TURN = 936 / 4

PostmortemDelay = 1000 * SR_TURN

CMSION_RESET = 0x60
FRONT_PANEL_INPUT = 0x76    # Event generated by EVR front panel input


# The pulse width for the I10 chicaine is half of 1007 FA periods, which
# translates into the following number thus:
#   1007    FA sample periods in 1/10 second (approximately)
#   53      Number of machine revolutions per FA update
I10_CHICAINE_WIDTH = 1007 * SR_TURN * 53 // 2


# Sets up the events common to all Diagnostics CIAs: BPM trigger, postmortem,
# and oscilloscope.
class _CommonEvents(EventReceiver):
    def __init__(self, Trigger, MachineClock, BpmDelay, id = 1):
        super().__init__(EventReceiverVME(), id = id)

        TriggerName, TriggerValue = Trigger

        # The postmortem event (OTP8) is generated from the MPS trip
        MonitorEvent(self.EventMap('MPS-TRIP',  self.MPS_TRIP,  8))

        # The oscilloscope and Libera triggers are generated from the selected
        # trigger source (either LB-TRG for Linac and Booster or BS-TRG for BtS
        # and Storage).  This trigger is also returned for use as the source of
        # other events.
        self.TickEvent = self.EventMap(TriggerName, TriggerValue, 0, 2)
        MonitorEvent(self.TickEvent)

        # The global DI-TRG event is also used to generate Libera triggers as
        # well as other special Diagnostics triggers.
        self.TriggerEvent = self.EventMap('DI-TRG', self.SR_DI_TRG)
        MonitorEvent(self.TriggerEvent)

        # Output timing definitions
        self.OTP(0, 'TRG-SCOPE',  BpmDelay + 25,   10)
        self.OTP(8, 'POSTMORTEM', int(PostmortemDelay), 125)
        self.OTP(2, 'TRG-BPM',    BpmDelay,        125)

        # Radiation monitor
        self.__radmon_events()

        # Front panel signals:
        #   TTL 0:  1MHz clock used for time stamping
        #   TTL 1:  Machine clock, either booster or storage
        #   TTL 2:  Libera trigger, on event line 2
        #   TTL 3:  Libera postmortem, on event line 1
        #   TTL 4:  Radiation Monitor accumulated dose reset
        #   ECL 0:  Oscilliscope trigger, on event line 0
        #   ECL 1:  (unused)
        self.FPS_TTL(0, self.MHzClock)    # 1MHz time reference
        self.FPS_TTL(1, MachineClock)     # Selected machine clock
        self.FPS_TTL(2, 'OTP2')           # BPM trigger
        self.FPS_TTL(3, 'OTP8')           # Postmortem
        self.FPS_TTL(4, 'PDP1')           # CMS ION reset
        self.FPS_ECL(0, 'OTP0')           # Oscilloscope trigger

        # Monitor the event receiver live status (this uses the linac heartbeat
        # event)
        self.EvrAlive = EvrAlive(self)
        self.LinacHeartbeat = self.EvrAlive.softEvent

        # Generate the event synchronisation framework.
        self.__EventSynchronisation(BpmDelay)



    # This constructs the event synchronisation framework for BPM events.  The
    # BPM trigger operates in two modes, "Normal" and "Synchronised".
    #
    # In Normal mode the normal selected background trigger (LB-TRG or
    # EXTR-PRE) is used to generate BPM triggers with the standard delay.
    #
    # In Synchronised mode we use the DI-TRG event to trigger a single shot
    # from the TS-RESET signal.  This will produce a trigger which is
    # precisely synchronised to the 1Hz clock.
    def __EventSynchronisation(self, BpmDelay):
        # The TS-RESET event runs at 1Hz, precisely synchronised to global
        # (GPS) time.  There is a local skew through the event system of a
        # microsecond or two, but this is uniform throughout.
        TsReset = self.EventMap('TS-RESET', self.TS_RESET)
        MonitorEvent(TsReset)

        # The so called BEAM-LOSS event, really a dedicated Diagnostics
        # hardware trigger, is used for Diagnostics experiments.  This is
        # optionally enabled onto OTP2.
        self.ExtraTrigger = self.EventMap('BEAM-LOSS', self.BEAM_LOSS)

        self.SetDevice()

        # Used to switch into normal mode.  Performs the following actions:
        #   - Disable TS-RESET output (in case it's still enabled)
        #   - Restore configured trigger delay for OTP2
        #   - Enable tick output, disable triggered output
        selectNormal = records.seq('TRIG:SELN',
            SELM = 'All',
            DOL1 = 0,           LNK1 = PP(self.ExtraTrigger.Enable_field(2)),
            DOL2 = 0,           LNK2 = PP(TsReset.Enable_field(2)),
            DOL3 = 0,           LNK3 = PP(self.TriggerEvent.Enable_field(2)),
            DOL4 = BpmDelay,    LNK4 = PP(self.OTP_Delay_field(2)),
            DOL5 = 1,           LNK5 = PP(self.TickEvent.Enable_field(2)))

        # Used to switch into synchronised mode:
        #   - Set trigger delay to 0
        #   - Disable tick and triggered output
        selectSynchronised = records.seq('TRIG:SELS',
            SELM = 'All',
            DOL1 = 0,           LNK1 = PP(self.ExtraTrigger.Enable_field(2)),
            DOL2 = 0,           LNK2 = PP(self.OTP_Delay_field(2)),
            DOL3 = 0,           LNK3 = PP(self.TickEvent.Enable_field(2)),
            DOL4 = 0,           LNK4 = PP(self.TriggerEvent.Enable_field(2)))

        # Used to switch into triggered mode:
        #   - Restore configured trigger delay
        #   - Disable tick output, enable triggered output
        selectTriggered = records.seq('TRIG:SELT',
            SELM = 'All',
            DOL1 = 0,           LNK1 = PP(self.ExtraTrigger.Enable_field(2)),
            DOL2 = 0,           LNK2 = PP(TsReset.Enable_field(2)),
            DOL3 = 0,           LNK3 = PP(self.TickEvent.Enable_field(2)),
            DOL4 = BpmDelay,    LNK4 = PP(self.OTP_Delay_field(2)),
            DOL5 = 1,           LNK5 = PP(self.TriggerEvent.Enable_field(2)))

        # Used to enable the extra diagnostics trigger mapped onto the
        # BEAM_LOSS event.
        selectExtraTrigger = records.seq('TRIG:EXTRA',
            SELM = 'All',
            DOL1 = 0,           LNK1 = PP(TsReset.Enable_field(2)),
            DOL2 = 0,           LNK2 = PP(self.TriggerEvent.Enable_field(2)),
            DOL3 = 0,           LNK3 = PP(self.TickEvent.Enable_field(2)),
            DOL4 = BpmDelay,    LNK4 = PP(self.OTP_Delay_field(2)),
            DOL5 = 1,           LNK5 = PP(self.ExtraTrigger.Enable_field(2)))

        # Mode selection: Normal or Synchronised.  Switching mode triggers the
        # appropriate one of the two select records above.
        modeSelection = records.mbbo('TRIG:MODE',
            OMSL = 'supervisory',
            VAL  = 1,
            ONVL = 1,   ONST = 'Normal',
            TWVL = 2,   TWST = 'Synchronised',
            THVL = 3,   THST = 'Triggered',
            FRVL = 4,   FRST = 'Extra Trigger')
        selectMode = records.fanout('TRIG:SEL',
            SELM = 'Specified',
            SELL = modeSelection,
            LNK1 = selectNormal,
            LNK2 = selectSynchronised,
            LNK3 = selectTriggered,
            LNK4 = selectExtraTrigger)
        modeSelection.FLNK = selectMode

        # On every TS-RESET event disable the TS-RESET output.  This ensures
        # that at most one hardware event is generated when this is enabled.
        TsResetDisable = records.seq('TRIG:TSD',
            SELM = 'All',
            DOL1 = 0,           LNK1 = PP(TsReset.Enable_field(2)))

        # On every DI-TRG event enable TS-RESET, but only if the current mode
        # is Synchronised.  This generates a trigger perfectly synchronised to
        # the 1Hz clock.
        TsResetEnable = records.calcout('TRIG:TSE',
            INPA = modeSelection,
            CALC = 'A=2',
            OOPT = 'When Non-zero',
            DOPT = 'Use OCAL',      OCAL = '1',
            OUT  = PP(TsReset.Enable_field(2)))
        TsReset.Bind(TsResetDisable)
        self.TriggerEvent.Bind(TsResetEnable)

        UnsetDevice()


    # Configures events for the radiation monitor events.
    def __radmon_events(self):
        # Radiation monitor reset.  This needs to be a 1 second pulse to
        # trigger reset of the radiation monitor.
        radmon_reset = self.EventMap('CMS:RESET', CMSION_RESET, 1)
        radmon_input = self.EventMap('CMS:INPUT', FRONT_PANEL_INPUT)
        self.PDP(1, 'RADMON', 0, 297620, 420)

        self.SetDevice()
        reset_ts = records.stringin('CMS:RESET:TS',
            DTYP = 'Soft Timestamp',
            TSE  = radmon_reset.event,
            INP  = '@%Y-%m-%d %H:%M:%S.%06f')
        input_ts = records.stringin('CMS:INPUT:TS',
            DTYP = 'Soft Timestamp',
            TSE  = radmon_input.event,
            INP  = '@%Y-%m-%d %H:%M:%S.%06f')
        add_autosave(input_ts, 'VAL')
        UnsetDevice()
        radmon_reset.Bind(reset_ts)
        radmon_input.Bind(input_ts)


# -----------------------------------------------------------------------------

# Linac

class LinacEvents(_CommonEvents):
    def __init__(self):
        super().__init__(LB_Trigger, BoosterClock, 19384)
        self.TickEvent.Append(3, 4, 10, 12, 13)

        self.OTP(3,  'TRG-CAM1',   9934, 500)    # Camera
        self.OTP(4,  'TRG-CAM2',   9934, 500)    # Camera
        self.OTP(10, 'TRG-ADC1',  18434, 125)    # ADC trigger
        self.OTP(12, 'TRG-ICT',   18350, 125)    # ICT
        self.OTP(13, 'TRG-PMT',    4934, 125)    # Beam loss monitors


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Booster

class BoosterEvents(_CommonEvents):
    def __init__(self, id):
        super().__init__(LB_Trigger, BoosterClock, 19384)

        if id == 1:
            self.BoosterOneEvents()
        elif id == 3:
            self.BoosterThreeEvents()

    def BoosterOneEvents(self):
        self.TickEvent.Append(3, 4, 9, 12, 13)
        MonitorEvent(self.EventMap('T0', self.LB0_DI_TRG, 10))

        self.DBUS(5)    # Bring Booster rev. clock onto back panel
        self.OTP(3,  'TRG-CAM1',  10000, 500)    # Camera
        self.OTP(4,  'TRG-AUX',       0, 250)    # Signal generator trigger
        self.OTP(9,  'TRG-CAM2',  12500, 500)
        self.OTP(12, 'TRG-ICT',   18350, 125)    # ICT
        self.OTP(13, 'TRG-PMT',    5000, 125)    # Beam loss monitors

        # The ADC trigger has to be very early so that the DCCT long
        # decimation filter can get a good run up (otherwise we lose the first
        # part of the signal after injection).  We do this by triggering the
        # ADC on T0 and delaying the appropriate (large) amount.  This also
        # means that the ICT readouts on the same ADC also need a large delay
        # (see BR01 ICT-03).
        #    Support in the ADC for pre-trigger readout would be helpful.
        self.OTP(10, 'TRG-ADC1',  5450000, 125)  # ADC trigger


    def BoosterThreeEvents(self):
        # The cameras in BR03C are used to monitor beam extraction, so need to
        # be triggered on the extract event.
        MonitorEvent(self.EventMap('EXTR-PRE', self.BS_DI_TRG, 3))
        self.OTP(3,  'TRG-CAM1',  131700, 500)   # Camera



# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Storage to Booster transfer

class BtsEvents(_CommonEvents):
    def __init__(self):
        super().__init__(BS_Trigger, BoosterClock, 139274)
        self.TickEvent.Append(3, 9, 10, 12, 13)

        self.DBUS(5)    # Bring both booster and machine clocks onto back
        self.DBUS(6)    # panel, as this location is transitional.
        self.OTP(3,  'TRG-CAM1',  131700, 500)    # Camera
        self.OTP(9,  'TRG-CAM2',  131700, 500)    #
        self.OTP(10, 'TRG-ADC1',  138000, 125)    # ADC trigger
        self.OTP(12, 'TRG-ICT',   138300, 125)    # ICT
        self.OTP(13, 'TRG-PMT',   124800, 125)    # PMT

        # Also generate a front panel event from SR_PRE_INJ for the
        # oscilliscope.  The delay on this event needs to track the delay
        # programmed into the power supply controller: this is used to monitor
        # the beam signal (on BS ICT-03) on the same trigger as the kicker
        # bumps.
        #    As (for unknown reasons) the tracked delay record updates
        # constantly we take care in the tracking calculation to only update
        # our own delay when it differs.
        self.EventMap('SR-PRE-INJ', self.SR_PRE_INJ, 4)
        self.OTP(4,  'SR-PRE-INJ', 0, 1250)
        self.FPS_ECL(1, 'OTP4')
        self.SetDevice()
        tracker = records.calcout('TRACK',
            CALC = 'A # B',
            OCAL = 'A',
            INPA = CP(ImportRecord('SR01S-PC-EVR-01:SET-HW').OTBD),
            INPB = self.OTP_Delay_field(4),
            OUT  = PP(self.OTP_Delay_field(4)),
            OOPT = 'When Non-zero',
            DOPT = 'Use OCAL',
            PINI = 'YES')
        self.UnsetDevice()



# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Storage Ring

class StorageEvents(_CommonEvents):
    BPM_DEFAULT_DELAY = 139274
    KICKER_DEFAULT_DELAY = 139250

    def __init__(self, cell, id=1):
        super().__init__(
            BS_Trigger, StorageClock, self.BPM_DEFAULT_DELAY, id=id)

        # Place 1MHz and machine clocks on rear panel for cells where needed
        self.DBUS(4)    # 1MHz
        self.DBUS(6)    # Storage ring machine clock

        # Generate any cell specific events
        extra_events = getattr(self, 'Storage_%02d_Events' % cell, None)
        if extra_events:
            extra_events()


    def Storage_01_Events(self):
        # Also generate camera trigger output on pre-extract event.
        self.TickEvent.Append(3, 9)
        self.OTP(3,  'TRG-CAM1',  131740, 500)    # Camera
        self.OTP(9,  'TRG-CAM2',  131740, 500)    # Camera


    def Storage_10_Events(self):
        # 10Hz chicaine trigger on back
        self.EventMap('I10-FASTCH', self.I10_FASTCH, 3)
        self.PDP(3, 'I10-FASTCH', 0, I10_CHICAINE_WIDTH, 1)
        self.FPS_ECL(1, 'PDP3')


    def Storage_23_Events(self):
        # Selectable trigger for TMBF
        self.tmbf_trigger_mode(5, self.BPM_DEFAULT_DELAY)

        # Blanking trigger for TMBF
        self.InjectEvent = self.EventMap('SR-PRE-INJ', self.SR_PRE_INJ, 9)
        self.OTP(9, 'BLANKING', 0, 125)

        # Generate kicker timing events
        for id, output in enumerate([3, 7]):
            self.pinger_trigger_mode(id, output, self.KICKER_DEFAULT_DELAY)


    # Multiplexor to select TMBF trigger.  The options are:
    #   SR-DI-TRG   (one shot trigger)
    #   BS-DI-TRG   (diagnostics 5Hz trigger)
    def tmbf_trigger_mode(self, output, default_delay):
        self.SetDevice()
        self.OTP(output, 'TMBF', default_delay, 125)

        tickEvent    = self.TickEvent.Enable_field(output)      # BS-DI
        triggerEvent = self.TriggerEvent.Enable_field(output)   # SR-DI

        selectOneShot = records.seq('TMBF:TRIG:SINGLE',
            SELM = 'All',
            DOL1 = 0,   LNK1 = PP(tickEvent),
            DOL2 = 1,   LNK2 = PP(triggerEvent))
        select5Hz = records.seq('TMBF:TRIG:5HZ',
            SELM = 'All',
            DOL1 = 0,   LNK1 = PP(triggerEvent),
            DOL2 = 1,   LNK2 = PP(tickEvent))

        modeSelection = records.mbbo('TMBF:TRIG:MODE',
            OMSL = 'supervisory',
            VAL  = 2,   PINI = 'YES',
            ONVL = 1,   ONST = 'One Shot: SR-DI',
            TWVL = 2,   TWST = 'Tick 5Hz: BS-DI')
        selectMode = records.fanout('TMBF:TRIG:SEL',
            SELM = 'Specified',
            SELL = modeSelection,
            LNK1 = selectOneShot,
            LNK2 = select5Hz)
        modeSelection.FLNK = selectMode
        UnsetDevice()


    # Multiplexor to select pinger trigger.  The options are:
    #   SR-DI-TRG   (one shot trigger)
    #   BS-DI-TRG   (diagnostics 5Hz trigger)
    #   10HZ-DIAG   (also called BEAM_LOSS for historical reasons)
    #   SR-PRE-INJ  (storage ring injection event)
    def pinger_trigger_mode(self, id, output, default_delay):
        self.SetDevice()
        # Add the requested output to the pre-extract trigger and
        # configure it, but leave it disabled by default.
        self.OTP(output, 'PINGER%d' % (id + 1),
            default_delay, 125, enabled = False)

        tickEvent    = self.TickEvent.Enable_field(output)      # BS-DI
        triggerEvent = self.TriggerEvent.Enable_field(output)   # SR-DI
        extraTrigger = self.ExtraTrigger.Enable_field(output)   # 10HZ-DIAG
        injectTrigger = self.InjectEvent.Enable_field(output)   # SR-PRE-INJ

        # The pinger trigger is selected from one of four independent
        # inputs, similar to the TRIG:MODE selection.  Note that we disable all
        # other sources before enabling our selected target to avoid a spurious
        # double trigger.
        selectOneShot = records.seq('PING%d:TRIG:SINGLE' % (id + 1),
            SELM = 'All',
            DOL1 = 0,   LNK1 = PP(tickEvent),
            DOL2 = 0,   LNK2 = PP(extraTrigger),
            DOL3 = 0,   LNK3 = PP(injectTrigger),
            DOL4 = 1,   LNK4 = PP(triggerEvent))
        select5Hz = records.seq('PING%d:TRIG:5HZ' % (id + 1),
            SELM = 'All',
            DOL1 = 0,   LNK1 = PP(triggerEvent),
            DOL2 = 0,   LNK2 = PP(extraTrigger),
            DOL3 = 0,   LNK3 = PP(injectTrigger),
            DOL4 = 1,   LNK4 = PP(tickEvent))
        select10Hz = records.seq('PING%d:TRIG:10HZ' % (id + 1),
            SELM = 'All',
            DOL1 = 0,   LNK1 = PP(tickEvent),
            DOL2 = 0,   LNK2 = PP(triggerEvent),
            DOL3 = 0,   LNK3 = PP(injectTrigger),
            DOL4 = 1,   LNK4 = PP(extraTrigger))
        selectInject = records.seq('PING%d:TRIG:PRE-INJ' % (id + 1),
            SELM = 'All',
            DOL1 = 0,   LNK1 = PP(tickEvent),
            DOL2 = 0,   LNK2 = PP(triggerEvent),
            DOL3 = 0,   LNK3 = PP(extraTrigger),
            DOL4 = 1,   LNK4 = PP(injectTrigger))

        modeSelection = records.mbbo('PING%d:TRIG:MODE' % (id + 1),
            OMSL = 'supervisory',
            VAL  = 1,
            ONVL = 1,   ONST = 'One Shot: SR-DI',
            TWVL = 2,   TWST = 'Tick 5Hz: BS-DI',
            THVL = 3,   THST = 'Fast 10Hz',
            FRVL = 4,   FRST = 'SR-PRE-INJ')
        selectMode = records.fanout('PING%d:TRIG:SEL' % (id + 1),
            SELM = 'Specified',
            SELL = modeSelection,
            LNK1 = selectOneShot,
            LNK2 = select5Hz,
            LNK3 = select10Hz,
            LNK4 = selectInject)
        modeSelection.FLNK = selectMode
        UnsetDevice()
